
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/locker777/config-repo.git
          username: locker777
          password: locker777@free
          basedir: E:/workspaces/springConfigSpace/config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
#basedir 从git下载的配置会存到这个目录3

