
#eureka客户端服务地址配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  register-with-eureka 让注册中心不显示eureka注册的信息
    register-with-eureka: false
# 实时判断服务是否已经不在线，由于默认eureka会认为服务活着而显示，建议生产不要设置false
  server:
    enable-self-preservation: false
#eureka客户端服务名配置
spring:
  application:
    name: eureka
#eureka 端口
server:
  port: 8761

#两台集群1注册2,2注册1
#三台集群1注册2、3,2注册1、3,3注册1、2

#eureka有心跳检测功能、健康监测和负载均衡
#eureka高可用，生产建议两台以上