
#eureka服务端地址配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  自定义访问域名结果显示http://clientname/....
#  instance:
#    hostname: clientname
spring:
  application:
    name: client
