
spring:
  application:
    name: product
  datasource:
    url: jdbc:mysql://192.168.115.142:3306/springcloud_sell?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    dialect: org.hibernate.dialect.MySQLDialect
  jpa:
    show-sql: false
eureka:
  client:
    service-url: http://127.0.0.1:8761/eureka

